version: 2
jobs:
  build-backend:
    working_directory: /go/src/github.com/cthit/speakIT/backend
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout:
          path: /go/src/github.com/cthit/speakIT/
      - run: go get -d
      - run: go build *.go

  build-frontend:
    working_directory: ~/speakIT/frontend
    docker:
      - image: circleci/node:8.1.2
    steps:
      - checkout:
          path: ~/speakIT
      - run: npm install
      - run: npm run build
      - run: npm run test
      - run: tar -czvf build.tar.gz build/*
      - store_artifacts:
          path: build.tar.gz
workflows:
  version: 2
  build:
    jobs:
      - build-backend
      - build-frontend